config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root 'welcome#index'
  
  resources :teachers, only: [:index, :show, :update], path: 'profesores', as: 'user', controller: :users do
		resources :teacher_comments
  end

  resources :students, only: [:index, :show], path: 'alumnos', controller: :users

  resources :courses, only: [:index, :show], path:'cursos', path_names: { new: 'crear', edit: 'editar' } do
    resources :comments
  end

  devise_for :users, path: 'usuario', path_names: {
		sign_in: 'ingresar', sign_out: 'salir', 
		password: 'contraseña', confirmation: 'verificar',
		sign_up: 'registro', edit: 'editar'
  }
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_rich_text :comment
  validates :comment, presence: true
  
  belongs_to :course
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates_uniqueness_of :nrc, :name
end

app/models/profesor.rb
class Profesor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/teacher_comment.rb
class TeacherComment < ApplicationRecord
  has_rich_text :teacher_comment
  validates :teacher_comment, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :teacher_comments, dependent: :destroy

  validates_uniqueness_of :id, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :is_student?
	
	def is_student?
    current_user.role == 'Alumno' if user_signed_in?
  end
	
	def after_sign_in_path_for(resource)
		courses_path
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  # POST /comments
  # POST /comments.json
  def create
    @course = Course.find(params[:course_id])
    @comment = @course.comments.new(params.require(:comment).permit(:comment, :id, :user_id))
    if @comment.save
      @course.save
    end
    redirect_to @course
  end

  # GET /comments/1/edit
  def edit
    @course = Course.find(params[:course_id])
    @comment = @course.comments.find(params[:id])
    redirect_to @course
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @course = Course.find(params[:course_id])
    @comment = @course.comments.find(params[:id])
    redirect_to @course
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @course = Course.find(params[:course_id])
    @comment = @course.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
    redirect_to @course
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
		@teacher_courses = []
    @teacher_courses_array = User.find(current_user.id).courses
    @teacher_courses_array.each do |i| 
      @teacher_courses<<[i, Course.find(i).nrc, Course.find(i).name]
    end

    if is_student?
      redirect_to student_path(current_user.id)
    else  
      redirect_to user_path(current_user.id)
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @comment = Comment.new
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:nrc, :name, :comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def before_login
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end
  
  def after_login
    session[:previous_url] || root_path
  end
end

app/controllers/teacher_comments_controller.rb
class TeacherCommentsController < ApplicationController
  before_action :authenticate_user!
  # POST /comments
  # POST /comments.json
  def create
    @user = User.find(params[:user_id])
    @teacher_comment = @user.teacher_comments.new(params.require(:teacher_comment).permit(:teacher_comment, :id, :user_id))
    if @teacher_comment.save
      @user.save
    end
    redirect_to @user 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	helper_method :is_student?
	before_action :set_user, only: [:show, :edit, :update]

	def index
		@courses = Course.all.sort
    @teachers = User.all.where(role:"Profesor").sort
    @users = User.all.where(role:"Alumno").sort
		if is_student? 
			render "student_index"
		else
			render "teacher_index"
		end
	end

  def show
    @comment = Comment.new
    @teacher_comment = TeacherComment.new
    x=0
    suma=0
		@teacher_courses = []
    @courses_count = Course.all.count
    @inscritos_count = Course.all.count
    @teacher_name = User.find(params[:id]).name
    @teacher_lastname = User.find(params[:id]).last_name
    @teacher_email = User.find(params[:id]).email
    @teacher_courses_array = User.find(params[:id]).courses
    @teacher_courses_array.each do |i| 
      @teacher_courses<<[i, Course.find(i).nrc, Course.find(i).name]
    end
    @teacher_evaluations = User.find(params[:id]).rating

    @teacher_evaluations.each do |evaluation, user|
      suma += evaluation
      x += 1
    end
    @evaluation_avg = suma/x if x!=0

		if request.fullpath==student_path(current_user.id)
			render "student_show"
    else
			render "teacher_show"
		end
  end

  def update
	end
	
	private

	def set_user
		@user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="card">
	<div class="card-body">
		<h5><%= User.find(comment.user_id).name %></h5>
		<%= comment.comment %>
		<small> El <%= User.find(comment.user_id).role %> comentó el <%= comment.created_at.strftime("%m/%d/%Y a las %H:%M") %></small>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@course, @user, @comment]) do |form| %>
  <%= form.hidden_field :user_id, value:"#{current_user.id}" %> 
  <div class="field bg-white mt-3">
    <%= form.rich_text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar' , class: 'btn btn-primary mt-2' %>
  </div>
<% end %>

app/views/comments/_new.html.erb
<%= render 'comments/form', comment: @comment %>

app/views/comments/edit.html.erb
<%= render 'comments/form', comment: @comment %>

app/views/courses/_index.html.erb
<table class="table table-dark">
	<thead>
		<tr>
			<th scope="col">NRC</th>
			<th scope="col">Nombre</th>
		</tr>
	</thead>
	<tbody>
		<% @teacher_courses.each do |i, course_nrc, course_name| %>
			<tr>
				<td><%= course_nrc %></td>
				<td><%= course_name %></td>
				<td><%= link_to 'Ver', course_path(i), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
  </tbody>
</table>

app/views/courses/show.html.erb
<h1 class="center" style="color:white !important; margin-top: 2rem;"><%= @course.name %></h1>

<p style="color: white;">
  <strong>NRC Curso:</strong>
  <%= @course.nrc %>
</p>

<%= link_to "Volver", request.referer.present? ? request.referer : root_path, class:"btn btn-warning" %> 

<div class="container mt-3 divider updates mb-3">
  <h3 class='darko pb-2 label-title'>Foro del curso</h3>
  <%= render @course.comments %>
</div>

<div class="container bg-white mt-3 mb-5 divider">
  <h3 class='darko pt-2 label-title'>Comentar</h3>
  <div class="comment-form mt-4 pb-3">
    <%= render 'comments/form', comment: @comment %>
  </div>
</div>

app/views/layouts/_background.slim
#bg

app/views/layouts/_error.slim
p.notice = notice
p.alert = alert

app/views/layouts/_head.slim
head
  meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
  meta charset="utf-8"
  meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
  meta http-equiv="x-ua-compatible" content="ie=edge"
  title = (yield(:title) + " | " unless yield(:title).blank?).to_s + "Comunidad UNAB"
  = csrf_meta_tags
  = csp_meta_tag

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  = favicon_link_tag asset_path('boca.png')

app/views/layouts/_navbar.slim
ul.nav.justify-content-end.bg-blue
	- unless request.fullpath=='/'
		li.nav-item.nav-align
			= link_to 'Volver al inicio', root_path, class: "nav-item nav-link inicio"
	- if user_signed_in?
		- unless current_user.nil?
			- if is_student?
				- unless request.fullpath=='/profesores'
					li.nav-item.nav-align
						= link_to 'Mis profesores', user_index_path, class: "nav-item nav-link"
				- unless request.fullpath==student_path(current_user.id)
					li.nav-item.nav-align
						= link_to 'Mi perfil', student_path(current_user.id), class: "nav-item nav-link perfil"
			- else
				- unless request.fullpath=='/alumnos'
					li.nav-item.nav-align
						= link_to 'Mis alumnos', students_path, class: "nav-item nav-link"
				- unless request.fullpath==user_path(current_user.id)
					li.nav-item.nav-align
						= link_to 'Mi perfil', user_path(current_user.id), class: "nav-item nav-link perfil"
      	li.nav-item.nav-align
        	= link_to 'Salir', destroy_user_session_path, method: :delete, class: "nav-item nav-link salir"
	- else
		- unless request.fullpath=='/usuario/ingreso'
			li.nav-item.nav-align
				= link_to 'Ingreso', new_user_session_path, class: "nav-item nav-link"
		- unless request.fullpath=='/usuario/registro'
			li.nav-item.nav-align
				= link_to 'Registro', new_user_registration_path, class: "nav-item nav-link"

app/views/layouts/application.slim
doctype html
html lang=I18n.locale 
  = render 'layouts/head'
  body
		= render partial: 'layouts/background'
		= render partial: 'layouts/navbar'

		.container.mw
			.row.justify-content-center
				.col
					= yield

app/views/teacher_comments/_form.html.erb
<%= form_for([@user, @teacher_comment]) do |form| %>
  <%= form.hidden_field :user_id, value:"#{current_user.id}" %> 
  <div class="field bg-white mt-3">
    <%= form.rich_text_area :teacher_comment %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar' , class: 'btn btn-primary mt-2' %>
  </div>
<% end %>

app/views/teacher_comments/_new.html.erb
<%= render 'teacher_comments/form', teacher_comment: @teacher_comment %>

app/views/teacher_comments/_teacher_comment.html.erb
<div class="card">
	<div class="card-body">
		<h5><%= User.find(teacher_comment.user_id).name %></h5>
		<%= teacher_comment.teacher_comment %>
		<small> El <%= User.find(teacher_comment.user_id).role %> evaluó el <%= teacher_comment.created_at.strftime("%m/%d/%Y a las %H:%M") %></small>
	</div>
</div>

app/views/teacher_comments/edit.html.erb
<%= render 'teacher_comments/form', teacher_comment: @teacher_comment %>

app/views/users/student.html.erb
<div class="container mt-3">
	<h3 class="center" style="color:white !important; margin-top: 2rem;">Mis cursos inscritos</h3>
	<h6 class="center" style="color:white !important;">Total: <%= @courses_count %></h6>

	<table class="table table-dark">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">NRC</th>
				<th scope="col">Nombre</th>
				<th scope="col">Profesor</th>
			</tr>
		</thead>
		<tbody>
			<% @courses.each do |course| %>
				<tr>
					<th scope="row"><%= course.id %></th>
					<td><%= course.nrc %></td>
					<td><%= course.name %></td>
					<td><%= course.teachers %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/student_index.html.erb
<!-- Mis Profesores / Muestra profesores de los cursos incritos -->
<div class="container mt-3">
	<h1 class="center" style="color:white !important; margin-top: 2rem;">Mis profesores</h1>

	<table class="table table-dark">
		<thead>
			<tr>
				<th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">Email</th>
			</tr>
		</thead>
		<tbody>
			<% @teachers.each do |user| %>
				<tr>
					<td><%= user.name %></td>
					<td><%= user.last_name %></td>
					<td><%= user.email %></td>
          <td><%= link_to 'Ver', user, class: "btn btn-primary" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/student_show.html.erb
<!-- Mi Perfil de Alumno / Cursos inscritos -->
<h1 class="center" style="color:white !important; margin-top: 2rem;"><b style="color:gold">Alumno:</b> <%= @teacher_name %> <%= @teacher_lastname %></h1>

<div class="card pr-2 pl-2 pt-3 pb-3">
  <div class="col-md-4">
    <h3>Correo electrónico</h3>
  </div>
  <div class="col-md-8">
    <div class="card-body">
      <%= @teacher_email %> 
    </div>
  </div>
</div>

<div class="card pr-2 pl-2 pt-3 mb-4">
  <div class="col-md-6">
    <h3>Cursos inscritos del período</h3>
  </div>
  <div class="col-12">
    <div class="card-body">
      <%= render 'courses/index.html.erb' %>
    </div>
  </div>
</div>

app/views/users/teacher.html.erb
<div class="container mt-3">
	<h3 class="center" style="color:white !important; margin-top: 2rem;">Alumnos inscritos en mis cursos</h3>
	<h6 class="center" style="color:white !important;">Total: <%= @users_count %></h6>

	<table class="table table-dark">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Nombre</th>
				<th scope="col">Apellido</th>
				<th scope="col">Correo Electrónico</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<th scope="row"><%= user.id %></th>
					<td><%= user.name %></td>
					<td><%= user.last_name %></td>
					<td><%= user.email %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/teacher_index.html.erb
<!-- Mis alumnos / Alumnos inscritos en mis cursos -->
<div class="container mt-3">
	<h1 class="center" style="color:white !important; margin-top: 2rem;">Alumnos inscritos en mis cursos</h1>

	<table class="table table-dark">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Nombre</th>
				<th scope="col">Apellido</th>
				<th scope="col">Correo Electrónico</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<th scope="row"><%= user.id %></th>
					<td><%= user.name %></td>
					<td><%= user.last_name %></td>
					<td><%= user.email %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/teacher_show.html.erb
<!-- Mi perfil de Profesor / Cursos impartidos y evaluaciones de ellos -->
<h1 class="center" style="color:white !important; margin-top: 2rem;"><b style="color:gold">Profesor:</b> <%= @teacher_name %> <%= @teacher_lastname %></h1>

<%= link_to "Volver", user_index_path, class:"btn btn-warning mb-3" %> 

<div class="card pr-2 pl-2 pt-3 pb-3">
  <div class="col-md-4">
    <h3>Correo electrónico</h3>
  </div>
  <div class="col-md-8">
    <div class="card-body">
      <%= @teacher_email %> 
    </div>
  </div>
</div>

<div class="card pr-2 pl-2 pt-3 pb-3">
  <div class="col-md-6">
    <h3>Cursos dictados del período</h3>
  </div>
  <div class="col-md-6">
    <div class="card-body">
      <u><b>NRC</b> | Nombre curso</u>
      <br>
    	<% @teacher_courses.each do |i, course_nrc, course_name| %>
				<b><%= course_nrc %></b> | <%= course_name %> | <%= link_to 'Ver curso', course_path(i) %>
        <br>
			<% end %>
    </div>
  </div>
</div>

<%- if is_student? %>
  <div class="card pr-2 pl-2 pt-3">
    <div class="col-md-4">
      <h3>Evaluaciones</h3>
    </div>
    <div class="col-md-12">
      <div class="card-body">
        <h3 class="score">★ <b style="color:black"><%= @evaluation_avg %> es la evaluación promedio de este profesor</b></h3>
      </div>
    </div>
    <div class="container divider mb-3">
      <%= render @user.teacher_comments %>
    </div>
  </div>

  <div class="container bg-white mt-3 mb-5 divider">
    <h3 class='label-title'>Evaluar</h3>
    <div class="comment-form mt-4 pb-3">
      <%= render 'teacher_comments/form', teacher_comment: @teacher_comment %>
    </div>
  </div>
<% else %>
  <div class="card pr-2 pl-2 pt-3 mb-5">
    <div class="col-md-4">
      <h3>Evaluaciones</h3>
    </div>
    <div class="col-md-12">
      <div class="card-body">
        <% @teacher_evaluations.each do |evaluation, user| %>
          <h3 class="score">★ <b style="color:black"><%= evaluation %> - <%= User.find(user.to_i).email %></b></h3>
        <% end %>
      </div>
    </div>
    <div class="container divider mb-3">
      <%= render @user.teacher_comments %>
    </div>    
  </div>
<% end %>

app/views/welcome/index.html.erb
<div class='card mt-4'>
  <div class='row mt-3 pb-3 justify-content-center'>
    <div class='col-12 card-body ml-4 mr-4'>
      <% if user_signed_in? %>
        <h1>Bienvenido <%= current_user.name %></h1>
      	<h6>	- Usted se ha logueado como <%= current_user.role %></h6>
      <%else%>
        <h1>Bienvenido a la plataforma de feedback</h1>
        <h6>	- Si eres Alumno inicia sesión y podrás dejar tu calificación junto con tú opinión a los profesores de los ramos que tengas inscritos</p>
        <h6>	- Si eres Profesor inicia sesión y podrás ver tu evaluación como docente de los ramos dictados</p>
      <% end %>
    </div>
  </div>
</div>  